Models/Entities/Booking.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace UfsConnectBook.Models.Entities
{
    public class Booking
    {
        [Key] public int Id { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public TimeSpan? Duration { get; set; } = TimeSpan.FromSeconds(1);
        [Display(Name = "Facility")]
        public int FacilityId { get; set; }
        public Facility? Facility { get; set; }
        public DateTime? BookingDate { get; set; }
        public string? Status { get; set; }
        [ProtectedPersonalData]
        public string? userEmail { get; set; }
    }
}

Models/Entities/Review.cs
namespace UfsConnectBook.Models.Entities
{
    public class Review
    {
        public int ReviewId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public DateTime From { get; set; }
        public DateTime To { get; set; }
        public bool IsApproved { get; set; }
    }
}

Controllers/AdministratorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UfsConnectBook.Data;
using UfsConnectBook.Models.Entities;
using UfsConnectBook.Models.ViewModel;
using DinkToPdf;
using DinkToPdf.Contracts;
using System.IO;
using UfsConnectBook.Utilities;
using NPOI;
using System.Text;
using UfsConnectBook.Models;

namespace UfsConnectBook.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministratorController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly AppDbContext appDbContext;
        //private readonly IPdfGenerator _pdfGenerator;

        public AdministratorController(UserManager<AppUser> userManager,
        RoleManager<IdentityRole> roleManager,
        AppDbContext appDbContext)
        //IPdfGenerator pdfGenerator Inside the ctor
        {
            _userManager = userManager;
            _roleManager = roleManager;
            this.appDbContext = appDbContext;
            //_pdfGenerator = pdfGenerator;
        }


        public async Task<IActionResult> Index(string Message)
        {

            if (!string.IsNullOrWhiteSpace(Message))
                ViewBag.Message = Message;
            var users = appDbContext.Users.ToList();
            List<AppUser> managerUsers = new List<AppUser>();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, "Manager"))
                    managerUsers.Add(user);
            }
            return View(managerUsers);
        }
        public IActionResult CreateManager()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateManager(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (ModelState.IsValid)
            {
                var user =
                new AppUser
                {
                    Email = model.EmailAddress,
                    UserName = model.EmailAddress,
                    Name = model.Name,
                    Surname = model.Surname,
                    Identity = model.Identification
                };
                var result = await _userManager.CreateAsync(user,
                model.Password);

                if (result.Succeeded)
                {
                    string role = "Manager";

                    if (!await _roleManager.RoleExistsAsync(role))
                        await _roleManager.CreateAsync(new IdentityRole { Name = role });

                    await _userManager.AddToRoleAsync(user, role);
                    return RedirectToAction(nameof(Index),
                        new { Message = $"New Manager Created Successful. Email: {model.EmailAddress}. Password: {model.Password}" });
                }
            }
            ModelState.AddModelError("", "Failed to register manager user!");
            ViewBag.IsModelError = false;
            return View(model);
        }
        public IActionResult Orders(string Message)
        {


            if (!string.IsNullOrWhiteSpace(Message))
                ViewBag.Message = Message;

            var booking = appDbContext.Bookings.Where(s => s.userEmail!
            .Equals(User.Identity.Name) && s.Status != "Canceled").OrderByDescending(s => s.Id).ToList();
            for (int i = 0; i < booking.Count(); i++)
            {
                booking[i].Facility = appDbContext.Facilities.Find(booking[i].FacilityId);
            }
            return View(booking);
        }
        public async Task<IActionResult> Incharge(string Message)
        {


            if (!string.IsNullOrWhiteSpace(Message))
                ViewBag.Message = Message;
            var users = appDbContext.Users.ToList();
            List<AppUser> inchargeUsers = new List<AppUser>();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, "Incharge"))
                    inchargeUsers.Add(user);
            }
            return View(inchargeUsers);
        }
        public async Task<IActionResult> Users(string Message)
        {


            if (!string.IsNullOrWhiteSpace(Message))
                ViewBag.Message = Message;
            var users = appDbContext.Users.ToList();
            List<AppUser> appUsers = new List<AppUser>();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, "AppUser"))
                    appUsers.Add(user);
            }
            return View(appUsers);
        }
        public IActionResult AdminBookingHistory()
        {
            return View();
        }
        public IActionResult GeneratePdfReport()
        {
            var pdfContent = "Report generated";
            var pdfBytes = Encoding.UTF8.GetBytes(pdfContent);
            return File(pdfBytes, "application/pdf", "Report.pdf");

        }
        public IActionResult GenerateBookingHistoryReport()
        {
            var bookings = appDbContext.Bookings
                .Where(s => s.Status != "Canceled")
                .OrderByDescending(s => s.BookingDate)
                .ToList();
            return View("GenerateBookingHistoryReport", bookings);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteManagerUser(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        [HttpPost, ActionName("DeleteManagerUser")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ConfirmDeleteManagerUser(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var result = await _userManager.DeleteAsync(user);

            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index), new { Message = $"Manager user {user.Email} has been deleted successfully." });
            }


            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(user);
        }
        [HttpGet]
        public async Task<IActionResult> EditManagerUser(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                return NotFound();
            }

            var model = new EditUserModel
            {
                UserId = user.Id,
                Name = user.Name,
                Surname = user.Surname,
                EmailAddress = user.Email,
                Identification = user.Identity
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditManagerUser(EditUserModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByIdAsync(model.UserId);

            if (user == null)
            {
                return NotFound();
            }

            user.Name = model.Name;
            user.Surname = model.Surname;
            user.Email = model.EmailAddress;
            user.Identity = model.Identification;

            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index), new { Message = $"Manager user {user.Email} has been updated successfully." });
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            return View(model);
        }


    }
}


Controllers/FacilityController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UfsConnectBook.Data;
using UfsConnectBook.Models.Entities;

namespace UfsConnectBook.Controllers
{
    public class FacilityController : Controller
    {
        private readonly AppDbContext appDbContext;
        private readonly UserManager<AppUser> userManager;

        public FacilityController(AppDbContext appDbContext, UserManager<AppUser>
            userManager)
        {
            this.appDbContext = appDbContext;
            this.userManager = userManager;

        }
        public IActionResult Index()
        {
           

            var facilities = appDbContext.Facilities.ToList();
            for (int i = 0; i < facilities.Count(); i++)
            {
                facilities[i].Category = appDbContext.Category.Find(facilities[i].CategoryId);
            }
            return View(facilities);
        }
        public IActionResult Details(int FacilityId)
        {

            var facility = appDbContext.Facilities.Find(FacilityId);
            facility!.Category = appDbContext.Category.Find(facility.CategoryId);
            if (facility.Category.Name == "Gym")
            {
                facility.ImagePath = "/images/Gym.jpg";
            }
            else if (facility.Category.Name == "Laundry")
            {
                facility.ImagePath = "/images/LaundryR.jpg";
            }
            else if (facility.Category.Name == "Parking")
            {
                facility.ImagePath = "/images/ParkingSlots.jpg";
            }
            else if (facility.Category.Name == "Study")
            {
                facility.ImagePath = "/images/LibraryRoom.jpg";
            }

            else
            {
                facility.ImagePath = "/images/UfsMainPage1.jpg"; 
            }
            return View(facility);
        }
        public IActionResult Create()
        {
            
            PopulateDDL();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Facility facility)
        {
            
            if (!ModelState.IsValid)
            {
                PopulateDDL();
                return View(facility);
            }
            appDbContext.Facilities.Add(facility);
            appDbContext.SaveChanges();

            return RedirectToAction(nameof(Index),
                new { Message = $"New facility for has been created successful" });

        }
        public IActionResult Edit(int facilityId)
        {
            
            var facility = appDbContext.Facilities.Find(facilityId)!;
            facility.Category = appDbContext.Category.Find(facility.CategoryId);
            PopulateDDL();
            return View(facility);
        }
        [HttpPost]
        public IActionResult Edit(Facility facility)
        {
            
            if (!ModelState.IsValid)
            {
                PopulateDDL();
                return View(facility);
            }
            appDbContext.Facilities.Update(facility);
            appDbContext.SaveChanges();

            return RedirectToAction(nameof(Index),
                new { Message = $"Facility Updated Successful.." });

        }
        public IActionResult Delete(int facilityId)
        {
            
            var facility = appDbContext.Facilities.Find(facilityId)!;
            facility.Category = appDbContext.Category.Find(facility.CategoryId);
            return View(facility);
        }
        [HttpPost]
        public IActionResult Delete(Facility facility, int facilityId)
        {
            
            var _facility = appDbContext.Facilities.Find(facilityId)!;
            appDbContext.Facilities.Remove(_facility);
            appDbContext.SaveChanges();
            return RedirectToAction(nameof(Index),
            new { Message = $"Facility was deleted Successful.." });
        }
        private void PopulateDDL()
        {
            ViewBag.CategoryId = new SelectList(appDbContext.Category.ToList(), "Id", "Name");
        }
    }
}

Views/Manager/Approve.cshtml
@model Booking
@{
    ViewData["Title"] = "Approve Booking";
}
<h4>Approve Booking</h4>

<div>
    <h6>Are you sure you want to <b>Approve</b> this booking?</h6>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BookingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BookingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Model.StartTime.ToShortTimeString()
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Model.EndTime.ToShortTimeString()
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FacilityId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Facility!.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class="col-sm-10">
            @{
                var dur = Model.EndTime - Model.StartTime;
            }
            @dur
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Model.Status.ToString()
        </dd>
    </dl>
    <form asp-action="Approve" method="post">
        @Html.HiddenFor(model => model.Id)
        <input asp-route-bookingId="@Model.Id" type="submit" class="btn btn-success" value="Approve" />
        <a asp-action="Index" class="btn btn-secondary">Back</a>
    </form>
</div>

Views/Manager/Bookings.cshtml
@model IEnumerable<Booking>
@{}

   @* ViewData["Title"] = "Bookings";*@
   <style>
           .payment-button {
        background-color: #0000FF;
        border: none; 
        color: white;
        padding: 15px 32px; 
        text-align: center; 
        text-decoration: none;
        display: inline-block; 
        font-size: 15px; 
        margin: 4px 2px; 
        cursor: pointer; 
        border-radius: 25px; 
        transition: background-color 0.3s, transform 0.3s; 
    }

      
        .payment-button:hover {
            background-color: #ffc0cb;
            transform: scale(1.05);
        }
</style>


<div style="display: flex;">
    <div style="width: 30%;">
        <img src="~/images/Booking.png" alt="Bookings Image" style="width: 100%;" />
    </div>
    <div style="width: 70%;">
<h4>Booking History</h4>
<p> facility booking history</p>
<table class="table tabletable-hover table-striped">
    <thead>
        <tr>
            <th>Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Facility</th>
            <th>Duration</th>
            <th>Status</th>
            <th>User</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var booking in Model)
        {
            <tr>
                <td>@booking.BookingDate</td>
                <td>@booking.StartTime.ToShortTimeString()</td>
                <td>@booking.EndTime.ToShortTimeString()</td>
                <td>@booking.Facility!.Name</td>
                <td>
                    @{
                        var dur = booking.EndTime - booking.StartTime;
                    } @dur
                </td>
                <td>@booking.Status.ToString()</td>
                <td>@booking.userEmail.ToString()</td>
                <td>
                    @if (booking.Status == "Pending")
                    {
                        @if (User.IsInRole("Manager"))
                                {
                                    <a class="btn btn-success" asp-action="Approve" asp-route-bookingId="@booking.Id">Approve</a>
                                
                        }
                    }
                </td>

               @*  <td>
                       <a class="btn btn-success" asp-action="GeneratePdfReport" asp-controller="Administrator"> report</a>
                </td>*@


            </tr>
        }
    </tbody>

  
</table>
             
          @*<a class="btn btn-success" asp-action="GenerateBookingHistoryReport" asp-controller="Administrator"> Generate booking Report</a>*@
          @if (User.IsInRole("Admin"))
        {
            <form asp-controller="Administrator" asp-action="GenerateBookingHistoryReport" method="get">
                <button type="submit" class="payment-button">Generate booking Report</button>
            </form>
        }

           
 </div>
</div>

Views/Manager/ChangePasswordManager.cshtml
@model ChangePasswordViewModel

<h2>Change Password</h2>

<form asp-action="ChangePasswordManager" method="post">
    <div class="form-group">
        <label for="CurrentPassword">Current Password:</label>
        <input type="password" class="form-control" id="CurrentPassword" name="CurrentPassword" required>
    </div>
    <div class="form-group">
        <label for="NewPassword">New Password:</label>
        <input type="password" class="form-control" id="NewPassword" name="NewPassword" required>
    </div>
    <div class="form-group">
        <label for="ConfirmPassword">Confirm Password:</label>
        <input type="password" class="form-control" id="ConfirmPassword" name="ConfirmPassword" required>
    </div>
    <button type="submit" class="btn btn-primary">Change Password</button>
</form>

Views/Manager/CreateIncharge.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Manager | CreateIncharge";
}
@model RegisterModel
<section id="hero" class="clearfix">
    <div class="container d-flex h-100">
        <div class="row justify-content-center align-self-center" data-aos="fade-up">
            <div class="col-md-12" data-aos="zoom-in" data-aos-delay="100">

                <div class="form">

                    <h4>Create Incharge</h4>
                    <p>Please provide the details below to create a new account</p>

                    <form asp-action="CreateIncharge" asp-controller="Manager" method="post" role="form">
                        <div class="text-danger" asp-validation-summary="All"></div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6 col-sm-12">
                                    <input asp-for=Name type="text" class="form-control" placeholder="FirstName">
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <input asp-for=Surname type="text" class="form-control" placeholder="LastName">
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <input asp-for=EmailAddress type="email" class="form-control" placeholder="Email Address">
                        </div>
                        <div class="form-group mt-3">
                            <input asp-for=Identification type="text" class="form-control" placeholder="UFS Staff Number">
                        </div>
                        <div class="form-group mt-3">
                            <div class="row">
                                <div class="col-md-6 col-sm-12">
                                    <input asp-for=Password type="password" class="form-control" placeholder="Enter Password">
                                </div>
                                <div class="col-md-6 col-sm-12">
                                    <input asp-for=ConfirmPassword type="password" class="form-control" placeholder="Re-Enter Password">
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <button type="submit" class="btn btn-primary" title="Register">Create Account</button>
                        </div>
                        <br /> <small class="text-center"><a asp-action="Index">Back To List</a></small>

                    </form>

                </div>
            </div>
        </div>

    </div>
</section>

Views/Manager/Facilities.cshtml
@model IEnumerable<Facility>
@{
    ViewData["Title"] = "Facilities";
}
<h4>Available Facilities</h4>
<table class="table">
    <thead>
        <tr>
            <th>Facility ID</th>
            <th>Name</th>
            <th>Category</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var facility in Model)
        {
            <tr>
                <td>@facility.FacilityId</td>
                <td>@facility.Name</td>
                <td>@facility.Category!.Name</td>
                <td>
                    <a asp-controller="Facility" asp-action="Details" asp-route-FacilityId="@facility.FacilityId" class="text-primary fa fa-eye"></a>
                    <a asp-controller="Facility" asp-action="Edit" asp-route-FacilityId="@facility.FacilityId" class="text-warning fa fa-edit"></a>
                    <a asp-controller="Facility" asp-action="Delete" asp-route-FacilityId="@facility.FacilityId" class="text-danger fa fa-delete-left"></a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Manager/Index.cshtml
@model IEnumerable<AppUser>
@{
    ViewData["Title"] = "Manager | Users";
}
<h4>Manager Users</h4>
<a asp-action="CreateIncharge" class="btn btn-primary">Create User</a>
<table class="table">
    <thead>
        <tr>
            <th>Full Name</th>
            <th>Email</th>
            <th>Staff Number</th>
            <th>Role</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Name @user.Surname</td>
                <td>@user.Email</td>
                <td>@user.Identity</td>
                <td>
                    Incharge
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Manager/Review.cshtml
@model IEnumerable<FeedBack>

<div class="table-container">
    <table class="table table-bordered table-striped mt-3">
        <thead>
            <tr>
                <th><i class="fas fa-id-card" style="color: green;"></i> Feedback ID</th>
                <th><i class="fas fa-star" style="color: gold;"></i> Rating</th>
                <th><i class="fas fa-comment-alt" style="color: blue;"></i> Comments</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var rating in Model)
            {
                <tr>
                    <td>@rating.Id</td>
                    <td>
                        @for (int i = 0; i < 5; i++)
                        {
                            @if (i < rating.Number)
                            {
                                <span class="fas fa-star" style="color: gold;"></span>
                            }
                            else
                            {
                                <span class="far fa-star" style="color: gray;"></span>
                            }
                        }
                    </td>
                    <td>@rating.Comment</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Views/Manager/UsersWithPayments.cshtml
@model List<string>

<h1>Users without Payments</h1>

<ul>
    @foreach (var user in Model)
    {
            <li>@user</li>
    }
</ul>

Views/Manager/UsersWithoutPayments.cshtml
@model List<string>

<h1>Users with Payments</h1>

<ul>
    @foreach (var user in Model)
    {
        <li>@user</li>
    }
</ul>