Models/Entities/Facility.cs
using System.ComponentModel.DataAnnotations;

namespace UfsConnectBook.Models.Entities
{
    public class Facility
    {

        [Key]
        public int FacilityId { get; set; }
        [Required]
        public string? Name { get; set; }
        public int CategoryId { get; set; }
        public string? ImagePath { get; set; }
        public Catagory? Category { get; set; }
    }
}

Controllers/FacilityController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UfsConnectBook.Data;
using UfsConnectBook.Models.Entities;

namespace UfsConnectBook.Controllers
{
    public class FacilityController : Controller
    {
        private readonly AppDbContext appDbContext;
        private readonly UserManager<AppUser> userManager;

        public FacilityController(AppDbContext appDbContext, UserManager<AppUser>
            userManager)
        {
            this.appDbContext = appDbContext;
            this.userManager = userManager;

        }
        public IActionResult Index()
        {
           

            var facilities = appDbContext.Facilities.ToList();
            for (int i = 0; i < facilities.Count(); i++)
            {
                facilities[i].Category = appDbContext.Category.Find(facilities[i].CategoryId);
            }
            return View(facilities);
        }
        public IActionResult Details(int FacilityId)
        {

            var facility = appDbContext.Facilities.Find(FacilityId);
            facility!.Category = appDbContext.Category.Find(facility.CategoryId);
            if (facility.Category.Name == "Gym")
            {
                facility.ImagePath = "/images/Gym.jpg";
            }
            else if (facility.Category.Name == "Laundry")
            {
                facility.ImagePath = "/images/LaundryR.jpg";
            }
            else if (facility.Category.Name == "Parking")
            {
                facility.ImagePath = "/images/ParkingSlots.jpg";
            }
            else if (facility.Category.Name == "Study")
            {
                facility.ImagePath = "/images/LibraryRoom.jpg";
            }

            else
            {
                facility.ImagePath = "/images/UfsMainPage1.jpg"; 
            }
            return View(facility);
        }
        public IActionResult Create()
        {
            
            PopulateDDL();
            return View();
        }
        [HttpPost]
        public IActionResult Create(Facility facility)
        {
            
            if (!ModelState.IsValid)
            {
                PopulateDDL();
                return View(facility);
            }
            appDbContext.Facilities.Add(facility);
            appDbContext.SaveChanges();

            return RedirectToAction(nameof(Index),
                new { Message = $"New facility for has been created successful" });

        }
        public IActionResult Edit(int facilityId)
        {
            
            var facility = appDbContext.Facilities.Find(facilityId)!;
            facility.Category = appDbContext.Category.Find(facility.CategoryId);
            PopulateDDL();
            return View(facility);
        }
        [HttpPost]
        public IActionResult Edit(Facility facility)
        {
            
            if (!ModelState.IsValid)
            {
                PopulateDDL();
                return View(facility);
            }
            appDbContext.Facilities.Update(facility);
            appDbContext.SaveChanges();

            return RedirectToAction(nameof(Index),
                new { Message = $"Facility Updated Successful.." });

        }
        public IActionResult Delete(int facilityId)
        {
            
            var facility = appDbContext.Facilities.Find(facilityId)!;
            facility.Category = appDbContext.Category.Find(facility.CategoryId);
            return View(facility);
        }
        [HttpPost]
        public IActionResult Delete(Facility facility, int facilityId)
        {
            
            var _facility = appDbContext.Facilities.Find(facilityId)!;
            appDbContext.Facilities.Remove(_facility);
            appDbContext.SaveChanges();
            return RedirectToAction(nameof(Index),
            new { Message = $"Facility was deleted Successful.." });
        }
        private void PopulateDDL()
        {
            ViewBag.CategoryId = new SelectList(appDbContext.Category.ToList(), "Id", "Name");
        }
    }
}

Controllers/ManagerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UfsConnectBook.Data;
using UfsConnectBook.Models.Entities;
using UfsConnectBook.Models.ViewModel;
using UfsConnectBook.Models;
using Microsoft.AspNetCore.Authorization;

namespace UfsConnectBook.Controllers
{

    public class ManagerController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly AppDbContext appDbContext;
        private readonly IRepositoryWrapper wrapper;
        private readonly RoleManager<IdentityRole> _roleManager;
        public ManagerController(UserManager<AppUser> userManager,
        AppDbContext appDbContext,
        RoleManager<IdentityRole> roleManager,
        IRepositoryWrapper wrapper)
        {
            _userManager = userManager;
            this.appDbContext = appDbContext;
            _roleManager = roleManager;
            this.wrapper = wrapper;
        }
        [ActionName("Index")]
        public async Task<IActionResult> Index(string Message)
        {


            if (!string.IsNullOrWhiteSpace(Message))
                ViewBag.Message = Message;
            var users = appDbContext.Users.ToList();
            List<AppUser> inchargeUsers = new List<AppUser>();
            foreach (var user in users)
            {
                if (await _userManager.IsInRoleAsync(user, "Incharge"))
                    inchargeUsers.Add(user);
            }
            return View(inchargeUsers);
        }
        public IActionResult CreateIncharge()
        {


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateIncharge(RegisterModel model)
        {


            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if (ModelState.IsValid)
            {
                var user =
                new AppUser
                {
                    Email = model.EmailAddress,
                    UserName = model.EmailAddress,
                    Name = model.Name,
                    Surname = model.Surname,
                    Identity = model.Identification
                };
                var result = await _userManager.CreateAsync(user,
                model.Password);

                if (result.Succeeded)
                {
                    string role = "Incharge";

                    if (!await _roleManager.RoleExistsAsync(role))
                        await _roleManager.CreateAsync(new IdentityRole { Name = role });

                    await _userManager.AddToRoleAsync(user, role);
                    return RedirectToAction(nameof(Index),
                        new { Message = $"New Offier InCharge Created Successful. Email: {model.EmailAddress}. Password: {model.Password}" });
                }
            }
            ModelState.AddModelError("", "Failed to register user!");
            ViewBag.IsModelError = false;
            return View(model);
        }
        public IActionResult Bookings(string Message)
        {
            if (!string.IsNullOrEmpty(Message))
                ViewBag.Message = Message;


            var bookings = appDbContext.Bookings.ToList();
            for (int i = 0; i < bookings.Count(); i++)
                bookings[i].Facility = appDbContext.Facilities.Find(bookings[i].FacilityId);
            return View(bookings);
        }
        public IActionResult Approve(int bookingId)
        {

            return View(appDbContext.Bookings.Find(bookingId));
        }
        [HttpPost]
        public IActionResult Approve(int bookingId, Booking booking)
        {

            var _booking = appDbContext.Bookings.Find(bookingId);
            _booking!.Status = "Aproved";
            appDbContext.Bookings.Update(_booking);
            appDbContext.SaveChanges();
            TempData["BookingApproved"] = "Your booking has been approved.";
            TempData["NewNotification"] = true;
            return RedirectToAction(nameof(Index), new { Message = $"The booking for {_booking.userEmail} was approved and is now in progress!" });
        }
        public IActionResult Facilities()
        {
            var facilities = appDbContext.Facilities.ToList();
            for (int i = 0; i < facilities.Count(); i++)
            {
                facilities[i].Category = appDbContext.Category.Find(facilities[i].CategoryId);
            }
            return View(facilities);
        }
        [HttpGet]
        public IActionResult Review()
        {
            IEnumerable<FeedBack> feedBacks = (IEnumerable<FeedBack>)wrapper.Review.GetAll();

            return View(feedBacks);
        }
        //return View();
        [HttpGet]
        public IActionResult ChangePasswordManager()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ChangePasswordManager(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = await _userManager.FindByNameAsync(User.Identity.Name);

            if (user == null)
            {
                return NotFound();
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(user, model.CurrentPassword, model.NewPassword);

            if (changePasswordResult.Succeeded)
            {

                return RedirectToAction(nameof(Bookings), new { Message = "Password changed successfully." });
            }
            else
            {

                foreach (var error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(model);
            }
        }
        public IActionResult UsersWithPayments()
        {
            var usersWithPayments = appDbContext.Bookings
                .Where(b => b.Status == "Approved")
                .Select(b => b.userEmail)
                .Distinct()
                .ToList();
            return View(usersWithPayments);
        }

        public IActionResult UsersWithoutPayments()
        {
            var usersWithoutPayments = appDbContext.Bookings
                .Where(b => b.Status == "Pending" || b.Status == "Confirmed")
                .Select(b => b.userEmail)
                .Distinct()
                .ToList();
            return View(usersWithoutPayments);
        }


    }
}

Views/Facility/Create.cshtml
@model Facility
@{
    ViewData["Title"] = "Create Facility";
}
<h4>Create Facility</h4>

<form asp-action="Create" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label>Category</label>
        <select asp-items="@ViewBag.CategoryId" asp-for="CategoryId" class="form-control">
            <option>--- Select Category ---</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Facilities" asp-controller="Manager"> Back To List</a>
    </div>
</form>


Views/Facility/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}
@model Facility
<h4>Delete Facility</h4>
<div>
    <h5>Are you sure you want to delete this facility</h5>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category!.Name)
        </dd>
    </dl>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for=FacilityId />
    <input asp-route-facilityId="@Model.FacilityId" type="submit" class="btn btn-danger" value="Confirm" />
</form>
<p>
    <a asp-action="Facilities" asp-controller="Manager">Back to List</a>
</p>

Views/Facility/Details.cshtml
@{
    ViewData["Title"] = "Details";
}
@model Facility

<style>
    .background-image {
        background-image: url('/images/Bookings.png'); 
        background-size: cover; 
        background-repeat: no-repeat;
        background-position: center center;
        min-height: 60vh; 
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .content-container {
        background-color: rgba(255, 255, 255, 0.8); 
    }

    .facility-image {
        max-width: 700px; 
        max-height: 380px; 
        width: auto; 
        height: auto; }

    body {
       
        padding-bottom: 50px; 
    }
</style>

<body>
<div class="background-image">
    <div class="content-container">
        <img src="@Model.ImagePath" alt="Facility Image" class="facility-image" />
        <h3>Facility Details</h3>
        <p>The following are the details of the selected facility</p>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                Category
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category!.Name)
            </dd>
            <dt class="col-sm-2">
    Price
</dt>
<dd class="col-sm-10">
    R90
</dd>
        </dl>
        <p>
            <a asp-action="Index" asp-controller="Facility">See full list</a>
        </p>
    </div>
</div>
</body>

Views/Facility/Edit.cshtml
@model Facility
@{
    ViewData["Title"] = "Edit Facility";
}
<h4>Edit Booking</h4>

<form asp-action="Edit" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <input asp-for=FacilityId type="hidden" />
    <div class="form-group">
        <label>Category</label>
        <select asp-items="@ViewBag.CategoryId" asp-for="CategoryId" class="form-control">
            <option>--- Select Category ---</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save Changes</button>
        <a asp-action="Facilities" asp-controller="Manager"> Back To List</a>
    </div>
</form>


Views/Facility/Index.cshtml
@model IEnumerable<Facility>
@{
    ViewData["Title"] = "Facilities";
}
<h4>Avaialble facilities</h4>
<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Facility ID</th>
            <th>Name</th>
            <th>Category</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var facility in Model)
        {
            <tr>
                <td>@facility.FacilityId</td>
                <td>@facility.Name</td>
                <td>@facility.Category!.Name</td>
                <td>
                   
                    <a asp-action="Details" asp-route-FacilityId="@facility.FacilityId" class="text-primary ">View Facility</a>
                    @if (!User.IsInRole("AppUser"))
                    {
                        <a asp-action="Edit" asp-route-FacilityId="@facility.FacilityId" class="text-warning ">Edit facility </a>
                        <a asp-action="Delete" asp-route-FacilityId="@facility.FacilityId" class="text-danger ">Delete facility</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>